<?php
/**
 * AgreementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Sales;

/**
 * AgreementTest Class Doc Comment
 *
 * @category    Class */
// * @description Agreement
/**
 * @package     Spinen\ConnectWise\Clients\Sales
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgreementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Agreement"
     */
    public function testAgreement()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "sub_contract_company"
     */
    public function testPropertySubContractCompany()
    {

    }

    /**
     * Test attribute "sub_contract_contact"
     */
    public function testPropertySubContractContact()
    {

    }

    /**
     * Test attribute "parent_agreement_id"
     */
    public function testPropertyParentAgreementId()
    {

    }

    /**
     * Test attribute "customer_po"
     */
    public function testPropertyCustomerPo()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "restrict_location_flag"
     */
    public function testPropertyRestrictLocationFlag()
    {

    }

    /**
     * Test attribute "restrict_department_flag"
     */
    public function testPropertyRestrictDepartmentFlag()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "no_ending_date_flag"
     */
    public function testPropertyNoEndingDateFlag()
    {

    }

    /**
     * Test attribute "opportunity"
     */
    public function testPropertyOpportunity()
    {

    }

    /**
     * Test attribute "cancelled_flag"
     */
    public function testPropertyCancelledFlag()
    {

    }

    /**
     * Test attribute "date_cancelled"
     */
    public function testPropertyDateCancelled()
    {

    }

    /**
     * Test attribute "reason_cancelled"
     */
    public function testPropertyReasonCancelled()
    {

    }

    /**
     * Test attribute "sla_id"
     */
    public function testPropertySlaId()
    {

    }

    /**
     * Test attribute "work_order"
     */
    public function testPropertyWorkOrder()
    {

    }

    /**
     * Test attribute "internal_notes"
     */
    public function testPropertyInternalNotes()
    {

    }

    /**
     * Test attribute "application_units"
     */
    public function testPropertyApplicationUnits()
    {

    }

    /**
     * Test attribute "application_limit"
     */
    public function testPropertyApplicationLimit()
    {

    }

    /**
     * Test attribute "application_cycle"
     */
    public function testPropertyApplicationCycle()
    {

    }

    /**
     * Test attribute "application_unlimited_flag"
     */
    public function testPropertyApplicationUnlimitedFlag()
    {

    }

    /**
     * Test attribute "one_time_flag"
     */
    public function testPropertyOneTimeFlag()
    {

    }

    /**
     * Test attribute "cover_agreement_time"
     */
    public function testPropertyCoverAgreementTime()
    {

    }

    /**
     * Test attribute "cover_agreement_product"
     */
    public function testPropertyCoverAgreementProduct()
    {

    }

    /**
     * Test attribute "cover_agreement_expense"
     */
    public function testPropertyCoverAgreementExpense()
    {

    }

    /**
     * Test attribute "cover_sales_tax"
     */
    public function testPropertyCoverSalesTax()
    {

    }

    /**
     * Test attribute "carry_over_unused"
     */
    public function testPropertyCarryOverUnused()
    {

    }

    /**
     * Test attribute "allow_overruns"
     */
    public function testPropertyAllowOverruns()
    {

    }

    /**
     * Test attribute "expired_days"
     */
    public function testPropertyExpiredDays()
    {

    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {

    }

    /**
     * Test attribute "expire_when_zero"
     */
    public function testPropertyExpireWhenZero()
    {

    }

    /**
     * Test attribute "charge_to_firm"
     */
    public function testPropertyChargeToFirm()
    {

    }

    /**
     * Test attribute "employee_comp_rate"
     */
    public function testPropertyEmployeeCompRate()
    {

    }

    /**
     * Test attribute "employee_comp_not_exceed"
     */
    public function testPropertyEmployeeCompNotExceed()
    {

    }

    /**
     * Test attribute "comp_hourly_rate"
     */
    public function testPropertyCompHourlyRate()
    {

    }

    /**
     * Test attribute "comp_limit_amount"
     */
    public function testPropertyCompLimitAmount()
    {

    }

    /**
     * Test attribute "bill_cycle_id"
     */
    public function testPropertyBillCycleId()
    {

    }

    /**
     * Test attribute "bill_one_time_flag"
     */
    public function testPropertyBillOneTimeFlag()
    {

    }

    /**
     * Test attribute "bill_terms_id"
     */
    public function testPropertyBillTermsId()
    {

    }

    /**
     * Test attribute "invoicing_cycle"
     */
    public function testPropertyInvoicingCycle()
    {

    }

    /**
     * Test attribute "bill_to_company"
     */
    public function testPropertyBillToCompany()
    {

    }

    /**
     * Test attribute "bill_to_site"
     */
    public function testPropertyBillToSite()
    {

    }

    /**
     * Test attribute "bill_amount"
     */
    public function testPropertyBillAmount()
    {

    }

    /**
     * Test attribute "taxable"
     */
    public function testPropertyTaxable()
    {

    }

    /**
     * Test attribute "prorate_first_bill"
     */
    public function testPropertyProrateFirstBill()
    {

    }

    /**
     * Test attribute "bill_start_date"
     */
    public function testPropertyBillStartDate()
    {

    }

    /**
     * Test attribute "tax_code_id"
     */
    public function testPropertyTaxCodeId()
    {

    }

    /**
     * Test attribute "restrict_down_payment"
     */
    public function testPropertyRestrictDownPayment()
    {

    }

    /**
     * Test attribute "prorate_flag"
     */
    public function testPropertyProrateFlag()
    {

    }

    /**
     * Test attribute "invoice_description"
     */
    public function testPropertyInvoiceDescription()
    {

    }

    /**
     * Test attribute "top_comment"
     */
    public function testPropertyTopComment()
    {

    }

    /**
     * Test attribute "bottom_comment"
     */
    public function testPropertyBottomComment()
    {

    }

    /**
     * Test attribute "work_role"
     */
    public function testPropertyWorkRole()
    {

    }

    /**
     * Test attribute "work_type"
     */
    public function testPropertyWorkType()
    {

    }

    /**
     * Test attribute "project_type_id"
     */
    public function testPropertyProjectTypeId()
    {

    }

    /**
     * Test attribute "invoice_template_setup_id"
     */
    public function testPropertyInvoiceTemplateSetupId()
    {

    }

    /**
     * Test attribute "bill_time"
     */
    public function testPropertyBillTime()
    {

    }

    /**
     * Test attribute "bill_expenses"
     */
    public function testPropertyBillExpenses()
    {

    }

    /**
     * Test attribute "bill_products"
     */
    public function testPropertyBillProducts()
    {

    }

    /**
     * Test attribute "billable_time_invoice"
     */
    public function testPropertyBillableTimeInvoice()
    {

    }

    /**
     * Test attribute "billable_expense_invoice"
     */
    public function testPropertyBillableExpenseInvoice()
    {

    }

    /**
     * Test attribute "billable_product_invoice"
     */
    public function testPropertyBillableProductInvoice()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "period_type"
     */
    public function testPropertyPeriodType()
    {

    }

}
