<?php
/**
 * OpportunityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Sales;

/**
 * OpportunityTest Class Doc Comment
 *
 * @category    Class */
// * @description Opportunity
/**
 * @package     Spinen\ConnectWise\Clients\Sales
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OpportunityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Opportunity"
     */
    public function testOpportunity()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "expected_close_date"
     */
    public function testPropertyExpectedCloseDate()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "stage"
     */
    public function testPropertyStage()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "probability"
     */
    public function testPropertyProbability()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {

    }

    /**
     * Test attribute "campaign"
     */
    public function testPropertyCampaign()
    {

    }

    /**
     * Test attribute "primary_sales_rep"
     */
    public function testPropertyPrimarySalesRep()
    {

    }

    /**
     * Test attribute "secondary_sales_rep"
     */
    public function testPropertySecondarySalesRep()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "customer_po"
     */
    public function testPropertyCustomerPo()
    {

    }

    /**
     * Test attribute "pipeline_change_date"
     */
    public function testPropertyPipelineChangeDate()
    {

    }

    /**
     * Test attribute "date_became_lead"
     */
    public function testPropertyDateBecameLead()
    {

    }

    /**
     * Test attribute "closed_date"
     */
    public function testPropertyClosedDate()
    {

    }

    /**
     * Test attribute "closed_by"
     */
    public function testPropertyClosedBy()
    {

    }

    /**
     * Test attribute "total_sales_tax"
     */
    public function testPropertyTotalSalesTax()
    {

    }

    /**
     * Test attribute "ship_to_company"
     */
    public function testPropertyShipToCompany()
    {

    }

    /**
     * Test attribute "ship_to_contact"
     */
    public function testPropertyShipToContact()
    {

    }

    /**
     * Test attribute "ship_to_site"
     */
    public function testPropertyShipToSite()
    {

    }

    /**
     * Test attribute "bill_to_company"
     */
    public function testPropertyBillToCompany()
    {

    }

    /**
     * Test attribute "bill_to_contact"
     */
    public function testPropertyBillToContact()
    {

    }

    /**
     * Test attribute "bill_to_site"
     */
    public function testPropertyBillToSite()
    {

    }

    /**
     * Test attribute "billing_terms"
     */
    public function testPropertyBillingTerms()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {

    }

}
