<?php
/**
 * TicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Sales;

/**
 * TicketTest Class Doc Comment
 *
 * @category    Class */
// * @description Ticket
/**
 * @package     Spinen\ConnectWise\Clients\Sales
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Ticket"
     */
    public function testTicket()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "summary"
     */
    public function testPropertySummary()
    {

    }

    /**
     * Test attribute "record_type"
     */
    public function testPropertyRecordType()
    {

    }

    /**
     * Test attribute "board"
     */
    public function testPropertyBoard()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {

    }

    /**
     * Test attribute "phase"
     */
    public function testPropertyPhase()
    {

    }

    /**
     * Test attribute "wbs_code"
     */
    public function testPropertyWbsCode()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "site_name"
     */
    public function testPropertySiteName()
    {

    }

    /**
     * Test attribute "address_line1"
     */
    public function testPropertyAddressLine1()
    {

    }

    /**
     * Test attribute "address_line2"
     */
    public function testPropertyAddressLine2()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "state_identifier"
     */
    public function testPropertyStateIdentifier()
    {

    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "contact_name"
     */
    public function testPropertyContactName()
    {

    }

    /**
     * Test attribute "contact_phone_number"
     */
    public function testPropertyContactPhoneNumber()
    {

    }

    /**
     * Test attribute "contact_phone_extension"
     */
    public function testPropertyContactPhoneExtension()
    {

    }

    /**
     * Test attribute "contact_email_address"
     */
    public function testPropertyContactEmailAddress()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "sub_type"
     */
    public function testPropertySubType()
    {

    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {

    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "service_location"
     */
    public function testPropertyServiceLocation()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "required_date"
     */
    public function testPropertyRequiredDate()
    {

    }

    /**
     * Test attribute "budget_hours"
     */
    public function testPropertyBudgetHours()
    {

    }

    /**
     * Test attribute "opportunity"
     */
    public function testPropertyOpportunity()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "severity"
     */
    public function testPropertySeverity()
    {

    }

    /**
     * Test attribute "impact"
     */
    public function testPropertyImpact()
    {

    }

    /**
     * Test attribute "external_x_ref"
     */
    public function testPropertyExternalXRef()
    {

    }

    /**
     * Test attribute "po_number"
     */
    public function testPropertyPoNumber()
    {

    }

    /**
     * Test attribute "knowledge_base_category_id"
     */
    public function testPropertyKnowledgeBaseCategoryId()
    {

    }

    /**
     * Test attribute "knowledge_base_sub_category_id"
     */
    public function testPropertyKnowledgeBaseSubCategoryId()
    {

    }

    /**
     * Test attribute "allow_all_clients_portal_view"
     */
    public function testPropertyAllowAllClientsPortalView()
    {

    }

    /**
     * Test attribute "customer_updated_flag"
     */
    public function testPropertyCustomerUpdatedFlag()
    {

    }

    /**
     * Test attribute "automatic_email_contact_flag"
     */
    public function testPropertyAutomaticEmailContactFlag()
    {

    }

    /**
     * Test attribute "automatic_email_resource_flag"
     */
    public function testPropertyAutomaticEmailResourceFlag()
    {

    }

    /**
     * Test attribute "automatic_email_cc_flag"
     */
    public function testPropertyAutomaticEmailCcFlag()
    {

    }

    /**
     * Test attribute "automatic_email_cc"
     */
    public function testPropertyAutomaticEmailCc()
    {

    }

    /**
     * Test attribute "initial_description"
     */
    public function testPropertyInitialDescription()
    {

    }

    /**
     * Test attribute "initial_internal_analysis"
     */
    public function testPropertyInitialInternalAnalysis()
    {

    }

    /**
     * Test attribute "initial_resolution"
     */
    public function testPropertyInitialResolution()
    {

    }

    /**
     * Test attribute "contact_email_lookup"
     */
    public function testPropertyContactEmailLookup()
    {

    }

    /**
     * Test attribute "process_notifications"
     */
    public function testPropertyProcessNotifications()
    {

    }

    /**
     * Test attribute "skip_callback"
     */
    public function testPropertySkipCallback()
    {

    }

    /**
     * Test attribute "closed_date"
     */
    public function testPropertyClosedDate()
    {

    }

    /**
     * Test attribute "closed_by"
     */
    public function testPropertyClosedBy()
    {

    }

    /**
     * Test attribute "closed_flag"
     */
    public function testPropertyClosedFlag()
    {

    }

    /**
     * Test attribute "date_entered"
     */
    public function testPropertyDateEntered()
    {

    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {

    }

    /**
     * Test attribute "actual_hours"
     */
    public function testPropertyActualHours()
    {

    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {

    }

    /**
     * Test attribute "sub_billing_method"
     */
    public function testPropertySubBillingMethod()
    {

    }

    /**
     * Test attribute "sub_billing_amount"
     */
    public function testPropertySubBillingAmount()
    {

    }

    /**
     * Test attribute "sub_date_accepted"
     */
    public function testPropertySubDateAccepted()
    {

    }

    /**
     * Test attribute "date_resolved"
     */
    public function testPropertyDateResolved()
    {

    }

    /**
     * Test attribute "date_resplan"
     */
    public function testPropertyDateResplan()
    {

    }

    /**
     * Test attribute "date_responded"
     */
    public function testPropertyDateResponded()
    {

    }

    /**
     * Test attribute "resolve_minutes"
     */
    public function testPropertyResolveMinutes()
    {

    }

    /**
     * Test attribute "res_plan_minutes"
     */
    public function testPropertyResPlanMinutes()
    {

    }

    /**
     * Test attribute "respond_minutes"
     */
    public function testPropertyRespondMinutes()
    {

    }

    /**
     * Test attribute "is_in_sla"
     */
    public function testPropertyIsInSla()
    {

    }

    /**
     * Test attribute "knowledge_base_link_id"
     */
    public function testPropertyKnowledgeBaseLinkId()
    {

    }

    /**
     * Test attribute "resources"
     */
    public function testPropertyResources()
    {

    }

    /**
     * Test attribute "parent_ticket_id"
     */
    public function testPropertyParentTicketId()
    {

    }

    /**
     * Test attribute "has_child_ticket"
     */
    public function testPropertyHasChildTicket()
    {

    }

    /**
     * Test attribute "knowledge_base_link_type"
     */
    public function testPropertyKnowledgeBaseLinkType()
    {

    }

    /**
     * Test attribute "bill_time"
     */
    public function testPropertyBillTime()
    {

    }

    /**
     * Test attribute "bill_expenses"
     */
    public function testPropertyBillExpenses()
    {

    }

    /**
     * Test attribute "bill_products"
     */
    public function testPropertyBillProducts()
    {

    }

    /**
     * Test attribute "predecessor_type"
     */
    public function testPropertyPredecessorType()
    {

    }

    /**
     * Test attribute "predecessor_id"
     */
    public function testPropertyPredecessorId()
    {

    }

    /**
     * Test attribute "predecessor_closed_flag"
     */
    public function testPropertyPredecessorClosedFlag()
    {

    }

    /**
     * Test attribute "lag_days"
     */
    public function testPropertyLagDays()
    {

    }

    /**
     * Test attribute "lag_nonworking_days_flag"
     */
    public function testPropertyLagNonworkingDaysFlag()
    {

    }

    /**
     * Test attribute "estimated_start_date"
     */
    public function testPropertyEstimatedStartDate()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "mobile_guid"
     */
    public function testPropertyMobileGuid()
    {

    }

    /**
     * Test attribute "sla"
     */
    public function testPropertySla()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {

    }

}
