<?php
/**
 * ActivityTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Sales;

use \Spinen\ConnectWise\Clients\Sales\Configuration;
use \Spinen\ConnectWise\Clients\Sales\ApiClient;
use \Spinen\ConnectWise\Clients\Sales\ApiException;
use \Spinen\ConnectWise\Clients\Sales\ObjectSerializer;

/**
 * ActivityTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivityTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for salesActivitiesTypesCountGet
     *
     * .
     *
     */
    public function testSalesActivitiesTypesCountGet()
    {

    }

    /**
     * Test case for salesActivitiesTypesGet
     *
     * .
     *
     */
    public function testSalesActivitiesTypesGet()
    {

    }

    /**
     * Test case for salesActivitiesTypesIdDelete
     *
     * .
     *
     */
    public function testSalesActivitiesTypesIdDelete()
    {

    }

    /**
     * Test case for salesActivitiesTypesIdGet
     *
     * .
     *
     */
    public function testSalesActivitiesTypesIdGet()
    {

    }

    /**
     * Test case for salesActivitiesTypesIdPatch
     *
     * .
     *
     */
    public function testSalesActivitiesTypesIdPatch()
    {

    }

    /**
     * Test case for salesActivitiesTypesIdPut
     *
     * .
     *
     */
    public function testSalesActivitiesTypesIdPut()
    {

    }

    /**
     * Test case for salesActivitiesTypesPost
     *
     * .
     *
     */
    public function testSalesActivitiesTypesPost()
    {

    }

}
