<?php
/**
 * OpportunityNotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Sales;

use \Spinen\ConnectWise\Clients\Sales\Configuration;
use \Spinen\ConnectWise\Clients\Sales\ApiClient;
use \Spinen\ConnectWise\Clients\Sales\ApiException;
use \Spinen\ConnectWise\Clients\Sales\ObjectSerializer;

/**
 * OpportunityNotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpportunityNotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesCountGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesCountGet()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesGet()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesNoteIdDelete
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesNoteIdDelete()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesNoteIdGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesNoteIdGet()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesNoteIdPatch
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesNoteIdPatch()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesNoteIdPut
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesNoteIdPut()
    {

    }

    /**
     * Test case for salesOpportunitiesIdNotesPost
     *
     * .
     *
     */
    public function testSalesOpportunitiesIdNotesPost()
    {

    }

}
