<?php
/**
 * OpportunityRatingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sales API
 *
 * ConnectWise Sales API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Sales;

use \Spinen\ConnectWise\Clients\Sales\Configuration;
use \Spinen\ConnectWise\Clients\Sales\ApiClient;
use \Spinen\ConnectWise\Clients\Sales\ApiException;
use \Spinen\ConnectWise\Clients\Sales\ObjectSerializer;

/**
 * OpportunityRatingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Sales
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpportunityRatingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsCountGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsCountGet()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsGet()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsIdDelete
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsIdDelete()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsIdGet
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsIdGet()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsIdPatch
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsIdPatch()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsIdPut
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsIdPut()
    {

    }

    /**
     * Test case for salesOpportunitiesRatingsPost
     *
     * .
     *
     */
    public function testSalesOpportunitiesRatingsPost()
    {

    }

}
